---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "my-workload"
  namespace: "default"
  labels:
    app: "my-workload"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "my-workload"
  template:
    metadata:
      labels:
        app: "my-workload"
    spec:
      containers:
      - name: "tictac-image-sha256-1"
        image: "gcr.io/trainingmodule-285008/tictac-image@sha256:584b70096c989813abf616d02bcdc0006d2465ea8d9a63c2c42e97fc29565ab2"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "my-workload-hpa-tonu"
  namespace: "default"
  labels:
    app: "my-workload"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "my-workload"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

